---
title: "Public Garden"
author: "Miles Ott"
date: "12/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

looking at this blogpost : https://clauswilke.com/art/post/probabilistic-hatching

```{r}
library(tidyverse)
library(colorspace)
library(ggtheme)

colors<-c( "#71a14c", #green
           "#101f0c", #dark green
           "#e2dc46", #yellowy green
           "#fec382", #peachy
           "#6a810c", #olivey green
           "#6a810c", #pale blue
           "#74ac3d" #minty green
)
```




```{r}

# the polygon, two triangles touching in the middle
poly_x <- c(0, 1, 1, 0)
poly_y <- c(0, 1, 0, 1)

# the extent of the initial point cloud
xlim <- c(-.5, 1.5)
ylim <- c(-.5, 1.5)

make_hatch_1 <- function(radius = 0.1, radius_sd = 0.01, n = 1000) {
  expand_grid(
    x = seq(xlim[1], xlim[2], length.out = n),
    y = seq(ylim[1], ylim[2], length.out = n),
  ) %>%
    mutate(
      x = x + rnorm(n(), sd = 0.01),
      y = y + rnorm(n(), sd = 0.01),
      # randomly generate radius and angle
      r = rnorm(n(), mean = radius, sd = radius_sd),
      theta = runif(n(), max = 2 * pi),
      # place segment end points on circles around start points
      xend = x + r * cos(theta),
      yend = y + r * sin(theta),
      # test whether both start and end points are in polygon
      interior = (sp::point.in.polygon(x, y, poly_x, poly_y) == 1) &
        (sp::point.in.polygon(xend, yend, poly_x, poly_y))
    ) %>%
    filter(interior)
}



make_hatch_1(radius = 0.02, radius_sd = 0.01, n=100) %>%
  ggplot(aes(x, y)) + 
  geom_segment(aes(xend = xend, yend = yend), 
               size = .3, 
               alpha = 0.15, 
               color = "black") +
  coord_fixed() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background = 
          element_rect(fill="#f6eceb", colour='#f6eceb'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

```



```{r}
make_hatch_2 <- function(radius = 0.1, radius_sd = 0.02, min = 0, max = 2*pi,
                         size = 0.15, alpha = 0.1, filter_endpoints = TRUE, 
                         n = 50000) {
  tibble(
    # the initial point distribution now consists of three Gaussian clouds 
    x = c(rnorm(n, mean = 0.7, sd = 0.2), 
          rnorm(n, mean = 0.2, sd = 0.2), 
          rnorm(n, mean = 0.4, sd = 0.3)),
    y = c(rnorm(n, mean = 0.85, sd = 0.2), 
          rnorm(n, mean = 0.95, sd = 0.2), 
          rnorm(n, mean = 0.2, sd = 0.3))
  ) %>%
    mutate(
      r = rnorm(n(), mean = radius, sd = radius_sd),
      theta = runif(n(), min = min, max = max),
      xend = x + r * cos(theta),
      yend = y + r * sin(theta),
      interior = (sp::point.in.polygon(x, y, poly_y, poly_x) == 1) &
        (!filter_endpoints | sp::point.in.polygon(xend, yend, poly_y, poly_x)),
      # colors for the three Gaussian clouds
      color = rep(c("goldenrod3", "coral4", "olivedrab"), each = n),
      alpha = alpha,
      size = size
    ) %>%
    filter(interior)
}

# encapsulate plotting in a function, for simplicity of later code
paint <- function(data) {
  ggplot(data, aes(x, y, color = color, size = size, alpha = alpha)) + 
    geom_segment(aes(xend = xend, yend = yend)) +
    scale_color_identity(aesthetics = c("color", "size", "alpha")) +
    coord_fixed() +
    theme_void()
}

data1 <- make_hatch_1(radius = 0.02, radius_sd = 0.01) %>%
  mutate(
    color = "steelblue4",
    alpha = 0.15,
    size = 0.2
  )

# combine the two hatch patterns and plot
rbind(data1, make_hatch_2()) %>%
  paint()
```


```{r}

polygons<-function(color_shape, xmin, xmax, ymin, ymax, jitter, a){
   n.gon<-sample(c(4,6,6,6,6,10),1)
  half<-n.gon/2
  x<-c(rep(xmin, half), rep(xmax,half)) 
  y<-c(seq(ymax, ymin, length=half), seq(ymin, ymax, length=half))
  x<-x+c(runif(half, -jitter*1.3, jitter), runif(half, -jitter, jitter*1.2))
  y<-y+runif(n.gon, -jitter, jitter)
  shape<-geom_polygon(
              aes(
                x=x,
                y=y,
               ),
              fill=colors[color_shape],
              alpha=a)
  return(list(shape))
}

n.width<-30
n.height<-10
shapes<-data.frame(
  y.max.seq<-rep(seq(0,6, length = n.width), n.height),
  x.max.seq<-sort(rep(seq(0, 5, length =n.height), n.width), decreasing =FALSE),
  x.min.seq<-x.max.seq-5/n.height,
  y.min.seq<-y.max.seq -6/n.width,
  cols<- sample (1:7, n.width*n.height, replace=TRUE)
  )%>%
  purrr::pmap(., 
            ~polygons(
              color_shape = ..5,
              xmin        = ..3, 
              xmax        = ..2,
              ymin        = ..4,
              ymax        = ..1,
              jitter      = .04,
              a           = .6)
            )


n.width<-40
n.height<-11
shapes2<-data.frame(
  y.max.seq<-rep(seq(0.1,5.9, length = n.width), n.height),
  x.max.seq<-sort(rep(seq(0.3, 4.5, length =n.height), n.width), decreasing =FALSE),
  x.min.seq<-x.max.seq-5/n.height,
  y.min.seq<-y.max.seq -6/n.width,
  cols<- sample (1:7, n.width*n.height, replace=TRUE)
  )%>%
  purrr::pmap(., 
            ~polygons(
              color_shape = ..5,
              xmin        = ..3, 
              xmax        = ..2,
              ymin        = ..4,
              ymax        = ..1,
              jitter      = .3,
              a =.44)
            )

g<-ggplot()+ theme(panel.background = element_rect(fill="#F8F0E3", colour="#F8F0E3"),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank())+
  shapes+
  shapes2+
coord_fixed()+
  scale_x_continuous(limits = c(-.3,5.2), expand = c(0, 0)) +
  scale_y_continuous(limits = c(-.4,6.2), expand = c(0, 0))+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

png("van_Gogh/public_park2.png", width=4, height=6, res=500, units="in")
g
dev.off()

```

