---
title: "Public Garden"
author: "Miles Ott"
date: "12/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
colors<-c( "#71a14c", #green
           "#101f0c", #dark green
           "#e2dc46", #yellowy green
           "#fec382", #peachy
           "#6a810c", #olivey green
           "#6a810c", #pale blue
           "#74ac3d" #minty green
)
```





```{r}

brush_stroke<-function(color_shape, xmin, xmax, ymin, ymax, jitter, a){
   n.gon<-sample(c(4,6,6,6,6,10),1)
  half<-n.gon/2
  x<-c(rep(xmin, half), rep(xmax,half)) 
  y<-c(seq(ymax, ymin, length=half), seq(ymin, ymax, length=half))
  x<-x+c(runif(half, -jitter*1.3, jitter), runif(half, -jitter, jitter*1.2))
  y<-y+runif(n.gon, -jitter, jitter)
  shape<-geom_polygon(
              aes(
                x=x,
                y=y,
               ),
              fill=colors[color_shape],
              alpha=a)
  return(list(shape))
}

n.width<-30
n.height<-10
shapes<-data.frame(
  y.max.seq<-rep(seq(0,6, length = n.width), n.height),
  x.max.seq<-sort(rep(seq(0, 5, length =n.height), n.width), decreasing =FALSE),
  x.min.seq<-x.max.seq-5/n.height,
  y.min.seq<-y.max.seq -6/n.width,
  cols<- sample (1:7, n.width*n.height, replace=TRUE)
  )%>%
  purrr::pmap(., 
            ~brush_stroke(
              color_shape = ..5,
              xmin        = ..3, 
              xmax        = ..2,
              ymin        = ..4,
              ymax        = ..1,
              jitter      = .04,
              a           = .6)
            )


n.width<-40
n.height<-11
shapes2<-data.frame(
  y.max.seq<-rep(seq(0.1,5.9, length = n.width), n.height),
  x.max.seq<-sort(rep(seq(0.3, 4.5, length =n.height), n.width), decreasing =FALSE),
  x.min.seq<-x.max.seq-5/n.height,
  y.min.seq<-y.max.seq -6/n.width,
  cols<- sample (1:7, n.width*n.height, replace=TRUE)
  )%>%
  purrr::pmap(., 
            ~brush_stroke(
              color_shape = ..5,
              xmin        = ..3, 
              xmax        = ..2,
              ymin        = ..4,
              ymax        = ..1,
              jitter      = .3,
              a =.44)
            )

g<-ggplot()+ theme(panel.background = element_rect(fill=colors[1], colour=colors[1]),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank())+
  shapes+
  shapes2+
coord_fixed()+
  scale_x_continuous(limits = c(-.3,5.2), expand = c(0, 0)) +
  scale_y_continuous(limits = c(-.4,6.2), expand = c(0, 0))+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

png("public_park1.png", width=4, height=6, res=500, units="in")
g
dev.off()

```

