---
title: "Blaze 4"
author: "Miles Ott"
date: "3/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
```


```{r}
circle<-function(x, y, r, n, offset){
  theta<-seq(0,2*pi,length=n+1)
  #theta<-theta[-1]
  theta<-c(theta[offset+2:n ], theta[1:offset]) 
  xc<-sin(theta)*r +x
  yc<-cos(theta)*r +y
  this.circle<-as.data.frame(cbind(xc, yc))
  return(this.circle)
}
```


```{r}
n<-90
circle1<-circle(0, 1, 1, n, 0)
circle2<-circle(0, .95, .9, n, 0)
circle3<-circle(0, .93, .8, n, 0)
circle4<-circle(0, .9, .7, n, 0)
circle5<-circle(0, .85, .6, n, 0)
circle6<-circle(0, .8, .5, n, 0)
circle7<-circle(0, .75, .4, n, 0)
circle8<-circle(0, .7, .3, n, 0)
circle9<-circle(0, .65, .2, n, 0)
circle10<-circle(0, .6, .1, n, 0)

df<-data.frame(matrix(ncol = 8, nrow = n))
df1<-df
df2<-df
df3<-df
df4<-df
df5<-df
df6<-df
df7<-df
df8<-df
df9<-df

sequence<-seq(1, n, by=2)

index<-1
for (i in  sequence){
df1[index, ]<- 
  c(
    circle2$xc[i], circle1$xc[(i+2):(i+3)], circle2$xc[i+1],
    circle2$yc[i], circle1$yc[(i+2):(i+3)], circle2$yc[i+1]
    )
df2[index, ]<- 
  c(
    circle2$xc[i+1], circle3$xc[(i+3):(i+4)], circle2$xc[i+2],
    circle2$yc[i+1], circle3$yc[(i+3):(i+4)], circle2$yc[i+2]
    )
 df3[index, ]<-  c(
    circle4$xc[i], circle3$xc[(i+2):(i+3)], circle4$xc[i+1],
    circle4$yc[i], circle3$yc[(i+2):(i+3)], circle4$yc[i+1]
    )
 df4[index, ]<-  c(
    circle4$xc[i+1], circle5$xc[(i+3):(i+4)], circle4$xc[i+2],
    circle4$yc[i+1], circle5$yc[(i+3):(i+4)], circle4$yc[i+2]
    )
 df5[index, ]<-  c(
    circle6$xc[i], circle5$xc[(i+2):(i+3)], circle6$xc[i+1],
    circle6$yc[i], circle5$yc[(i+2):(i+3)], circle6$yc[i+1]
    )
  df6[index, ]<-  c(
    circle6$xc[i+1], circle7$xc[(i+3):(i+4)], circle6$xc[i+2],
    circle6$yc[i+1], circle7$yc[(i+3):(i+4)], circle6$yc[i+2]
    )
 df7[index, ]<-  c(
    circle8$xc[i], circle7$xc[(i+2):(i+3)], circle8$xc[i+1],
    circle8$yc[i], circle7$yc[(i+2):(i+3)], circle8$yc[i+1]
    )
df8[index, ]<-  c(
    circle8$xc[i+1], circle9$xc[(i+3):(i+4)], circle8$xc[i+2],
    circle8$yc[i+1], circle9$yc[(i+3):(i+4)], circle8$yc[i+2]
    )
 df9[index, ]<-  c(
    circle10$xc[i], circle9$xc[(i+2):(i+3)], circle10$xc[i+1],
    circle10$yc[i], circle9$yc[(i+2):(i+3)], circle10$yc[i+1]
    )
index<-index+1        
}  

df1[index, ]<- c(
    circle2$xc[n-1], circle1$xc[(1):(2)], circle2$xc[n],
    circle2$yc[n-1], circle1$yc[(1):(2)], circle2$yc[n]
    )



df2[index, ]<- 
  c(
    circle2$xc[n-2], circle3$xc[c(n,1)], circle2$xc[n-1],
    circle2$yc[n-2], circle3$yc[c(n,1)], circle2$yc[n-1]
    )

df2[index+1, ]<- 
  c(
    circle2$xc[n], circle3$xc[(2):(3)], circle2$xc[1],
    circle2$yc[n], circle3$yc[(2):(3)], circle2$yc[1]
    )




df3[index, ]<- c(
    circle4$xc[n-1], circle3$xc[(1):(2)], circle4$xc[n],
    circle4$yc[n-1], circle3$yc[(1):(2)], circle4$yc[n]
    )
df4[index, ]<- 
  c(
    circle4$xc[n-2], circle5$xc[c(n,1)], circle4$xc[n-1],
    circle4$yc[n-2], circle5$yc[c(n,1)], circle4$yc[n-1]
    )

df4[index+1, ]<- 
  c(
    circle4$xc[n], circle5$xc[(2):(3)], circle4$xc[1],
    circle4$yc[n], circle5$yc[(2):(3)], circle4$yc[1]
    )

df5[index, ]<- c(
    circle6$xc[n-1], circle5$xc[(1):(2)], circle6$xc[n],
    circle6$yc[n-1], circle5$yc[(1):(2)], circle6$yc[n]
    )
df6[index, ]<- 
  c(
    circle6$xc[n-2], circle7$xc[c(n,1)], circle6$xc[n-1],
    circle6$yc[n-2], circle7$yc[c(n,1)], circle6$yc[n-1]
    )

df6[index+1, ]<- 
  c(
    circle6$xc[n], circle7$xc[(2):(3)], circle6$xc[1],
    circle6$yc[n], circle7$yc[(2):(3)], circle6$yc[1]
    )


df7[index, ]<- c(
    circle8$xc[n-1], circle7$xc[(1):(2)], circle8$xc[n],
    circle8$yc[n-1], circle7$yc[(1):(2)], circle8$yc[n]
    )
df8[index, ]<- 
  c(
    circle8$xc[n-2], circle9$xc[c(n,1)], circle8$xc[n-1],
    circle8$yc[n-2], circle9$yc[c(n,1)], circle8$yc[n-1]
    )

df8[index+1, ]<- 
  c(
    circle8$xc[n], circle9$xc[(2):(3)], circle8$xc[1],
    circle8$yc[n], circle9$yc[(2):(3)], circle8$yc[1]
    )
df9[index, ]<- c(
    circle10$xc[n-1], circle9$xc[(1):(2)], circle10$xc[n],
    circle10$yc[n-1], circle9$yc[(1):(2)], circle10$yc[n]
    )


df<-rbind(df1[1:index, ], 
          df2[1:(index+1), ], 
          df3[1:index, ],
          df4[1:(index+1), ],
          df5[1:index, ], 
          df6[1:(index+1), ], 
          df7[1:index, ],
          df8[1:(index+1), ],
          df9[1:index,])

```

```{r}
g<-ggplot()+ theme(panel.background = element_rect(fill="#e5e5e3", colour='#e5e5e3'),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank())


shapes<-df%>%
  purrr::pmap(., 
            ~geom_polygon(aes(x=c(..1, ..2, ..3, ..4), 
                              y=c(..5, ..6, ..7, ..8)))
            )  
g<-g+shapes

g<-g+  coord_fixed()+
  scale_x_continuous(limits = c(-1,1), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,2), expand = c(0, 0))+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

png("Blaze_4_Bridget_Riley/Blaze_4.png", width=4, height=4, res=500, units="in")
g
dev.off()
```

